---
extends: default

rules:
  line-length:
    max: 200
    level: warning
  truthy:
    allowed-values: ["true", "false", "yes", "no"]
  comments:
    min-spaces-from-content: 1
  document-start: disable
  braces:
    max-spaces-inside: 1
  brackets:
    max-spaces-inside: 1
