---
- name: Check if SSH key exists
  ansible.builtin.stat:
    path: "{{ ssh_key }}"
  register: ssh_key_stat

- name: Generate SSH key
  ansible.builtin.command:
    cmd: "ssh-keygen -f {{ ssh_key }} -N ''"
  when: not ssh_key_stat.stat.exists

- name: Copy SSH key to each host if not already installed
  ansible.builtin.shell: |
    ssh-copy-id -i {{ ssh_key }}.pub -o StrictHostKeyChecking=no {{ ssh_user }}@{{ host_item }} || \
    echo "{{ host_item }}: Key already exists or another error occurred."
  loop: "{{ host_group }}"
  loop_control:
    loop_var: host_item
  register: ssh_copy_result
  ignore_errors: true

- name: Check for 'Key already exists' message
  ansible.builtin.fail:
    msg: "Failed to copy SSH key to {{ item.item }} due to an unexpected error."
  when: 
    - "'Key already exists or another error occurred.' not in item.stdout"
    - item.rc != 0
  loop: "{{ ssh_copy_result.results }}"
  loop_control:
    loop_var: item

- name: Wipe OSD devices on host
  ansible.builtin.command:
    cmd: "sudo wipefs --all /dev/{{ item }}"
  become: yes
  become_method: sudo
  loop: "{{ osd_devices }}"
  delegate_to: "{{ osd_host }}"

- name: Run preflight setup for Ceph
  include_tasks: cephadm-preflight.yml