---
- name: Check if SSH key exists
  ansible.builtin.stat:
    path: "{{ ssh_key }}"
  register: ssh_key_stat

- name: Generate SSH key
  ansible.builtin.command:
    cmd: "ssh-keygen -f {{ ssh_key }} -N ''"
  when: not ssh_key_stat.stat.exists

- name: Copy SSH key to each host
  ansible.builtin.command:
    cmd: "ssh-copy-id -i {{ ssh_key }} -o StrictHostKeyChecking=no {{ ssh_user }}@{{ item }}"
  loop: "{{ host_group }}"

- name: Wipe OSD devices on host
  ansible.builtin.command:
    cmd: "ssh -i {{ ssh_key }} {{ ssh_user }}@{{ osd_host }} 'sudo wipefs --all /dev/{{ item }}'"
  loop: "{{ osd_devices }}"

- name: Run preflight setup for Ceph
  include_tasks: cephadm-preflight.yml