---
- name: Check if SSH key exists
  ansible.builtin.stat:
    path: "{{ ssh_key }}"
  register: ssh_key_stat

- name: Generate SSH key
  ansible.builtin.command:
    cmd: "ssh-keygen -f {{ ssh_key }} -N ''"
  when: not ssh_key_stat.stat.exists
  delegate_to: localhost
  run_once: true

- name: Copy SSH key to each host if not already installed
  ansible.builtin.shell: |
    ssh-copy-id -i {{ ssh_key }}.pub -o StrictHostKeyChecking=no {{ ssh_user }}@{{ item }} \
    echo "SSH key copied successfully to {{ item }}." || \
    echo "Failed to copy SSH key to {{ item }}."
  loop: "{{ groups['clients'] }}"
  loop_control:
    loop_var: item
  register: ssh_copy_result
  delegate_to: localhost
  run_once: true

- name: Check for 'Key already exists' message
  ansible.builtin.fail:
    msg: "Failed to copy SSH key to {{ item.item }} due to an unexpected error."
  when: 
    - "'Key already exists or another error occurred.' not in item.stdout"
    - item.rc != 0
  loop: "{{ ssh_copy_result.results }}"
  loop_control:
    loop_var: item
  delegate_to: localhost
  run_once: true

- name: Wipe OSD devices on host
  ansible.builtin.command:
    cmd: "sudo wipefs --all /dev/{{ item }}"
  become: true
  loop: "{{ osd_devices }}"
  when: inventory_hostname in groups['osds']

- name: Run preflight setup for Ceph
  include_tasks: cephadm-preflight.yml