---
- name: Wipe OSD devices on host
  ansible.builtin.command: |
    ssh -i -o StrictHostKeyChecking=no -i {{ ssh_key_private }} "{{ ssh_user }}@{{ item.0 }}"
    sudo wipefs --all "/dev/{{ item.1 }}"
  loop: "{{ groups['osds'] | product(osd_devices) | list }}"
  loop_control:
    loop_var: item
    label: "{{ item.0 }} - /dev/{{ item.1 }}"
  when: inventory_hostname in groups['osds']

- name: Run preflight setup for Ceph
  include_tasks: cephadm-preflight.yml