- hosts: all
  become: true
  gather_facts: true
  roles:
    - role: ceph-common
      when: run_ceph_common | default(true) | bool
    - role: ceph-deploy
      when: run_ceph_deploy | default(true) | bool
      delegate_to: localhost
      run_once: true
      
