---
- name: Prepare and add OSDs
  block:
    - name: Add OSD on each device and wait for readiness
      ansible.builtin.shell: |
        sudo /usr/bin/ceph orch daemon add osd {{ osd_host }}:/dev/{{ item }}
        # Wait and check readiness logic here
      loop: "{{ osd_devices }}"
      delegate_to: "{{ admin_host }}"
