---
- name: Prepare and add OSDs on each device on OSD host
  ansible.builtin.command: |
    sudo ceph orch daemon add osd {{ hostvars[item]['ansible_host'] }}:/dev/{{ device }}
  loop: "{{ osd_devices }}"
  delegate_to: localhost
  loop_control:
    loop_var: device
