---
- name: Add and label hosts in the Ceph cluster
  block:
    - name: Ensure admin node's SSH public key is authorized on each host
      ansible.builtin.command: |
        ssh-copy-id -i /etc/ceph/ceph.pub -o StrictHostKeyChecking=no {{ ssh_user }}@{{ hostvars[item]['ansible_host'] }}
      loop: "{{ groups['clients'] }}"
      loop_control:
        loop_var: item

    - name: Add host to Ceph cluster and apply labels
      ansible.builtin.shell: |
        sudo ceph orch host add {{ item.hostname }} {{ hostvars[item.hostname]['ansible_host'] }}
        sudo ceph orch host label add {{ item.hostname }} {{ item.label }}
      loop:
        - { hostname: "{{ groups['admin'][0] }}", label: "mon,mgr" }
        - { hostname: "{{ groups['osds'][0] }}", label: "osd" }

    - name: Apply '_no_schedule' label to specific hosts
      ansible.builtin.shell: |
        sudo ceph orch host label add {{ item }} _no_schedule
      loop: "{{ groups['all'] }}"
      when: 
        - item not in groups['admin']
        - item not in groups['osds']
      loop_control:
        loop_var: item