---
- name: Ensure admin node's SSH public key is authorized on each host
  hosts: clients
  tasks:
    - name: Copy SSH public key to each client host
      ansible.builtin.command: |
        ssh-copy-id -f -i /etc/ceph/ceph.pub -o StrictHostKeyChecking=no {{ ssh_user }}@{{ inventory_hostname }}

- name: Add admin hosts to Ceph cluster and apply mon,mgr labels
  hosts: admin
  tasks:
    - name: Add host to Ceph cluster and apply labels
      ansible.builtin.shell: |
        sudo ceph orch host add {{ inventory_hostname }} {{ hostvars[inventory_hostname]['ansible_host'] }}
        sudo ceph orch host label add {{ inventory_hostname }} mon,mgr

- name: Add OSD hosts to Ceph cluster and apply osd label
  hosts: osds
  tasks:
    - name: Add host to Ceph cluster and apply labels
      ansible.builtin.shell: |
        sudo ceph orch host add {{ inventory_hostname }} {{ hostvars[inventory_hostname]['ansible_host'] }}
        sudo ceph orch host label add {{ inventory_hostname }} osd

- name: Apply '_no_schedule' label to specific hosts
  tasks:
    - name: Label hosts with '_no_schedule'
      ansible.builtin.shell: |
        sudo ceph orch host label add {{ inventory_hostname }} _no_schedule
      when: 
        - inventory_hostname not in groups['admin']
        - inventory_hostname not in groups['osds']
