---

- name: Add all host to Ceph cluster
  ansible.builtin.shell: |
    ceph orch host add {{ item }} {{ hostvars[item]['ansible_host'] }} || \
    echo "{{ item }}: Failed to {{ item }} add host to Ceph cluster 
  loop: "{{ groups['clients'] }}"
  loop_control:
    loop_var: item

- name: Add admin apply mon,mgr labels
  ansible.builtin.shell: |
    ceph orch host label add {{ item }} mon,mgr || \
    echo "{{ item }}: Failed to add and label as mon,mgr."
  loop: "{{ groups['admin'] }}"
  loop_control:
    loop_var: item

- name: Add OSD apply osd label
  ansible.builtin.shell: |
    ceph orch host label add {{ item }} osd || \
    echo "{{ item }}: Failed to add and label as osd."
  loop: "{{ groups['osds'] }}"
  loop_control:
    loop_var: item

- name: Label specific hosts with '_no_schedule'
  ansible.builtin.shell: |
    ceph orch host label add {{ item }} _no_schedule || \
    echo "{{ item }}: Failed to label as '_no_schedule'."
  loop: "{{ groups['clients'] }}"
  loop_control:
    loop_var: item
  when: item not in groups['admin'] and item not in groups['osds']
