---
- name: Prepare and add OSDs on each device on OSD host
  tasks:
  - name: Add OSDs for each device
    ansible.builtin.command: |
      sudo ceph orch daemon add osd {{ inventory_hostname }}:/dev/{{ device }}
    loop: "{{ osd_devices }}"
    loop_control:
      loop_var: device
    when: inventory_hostname in groups['osds']