- name: fail if admin is not defined
  fail:
    msg: "You must set the variable admin"
  when: groups['admin'] is undefined or groups['admin'] | length == 0

- name: get ssh public key from a file on the Ansible controller host
  when: cephadm_pubkey_path is defined
  block:
    - name: get details about {{ cephadm_pubkey_path }}
      stat:
        path: "{{ cephadm_pubkey_path }}"
      register: cephadm_pubkey_path_stat

    - name: fail if {{ cephadm_pubkey_path }} doesn't exist
      fail:
        msg: "{{ cephadm_pubkey_path }} doesn't exist or is invalid."
      when:
        - not cephadm_pubkey_path_stat.stat.exists | bool
          or not cephadm_pubkey_path_stat.stat.isreg | bool

- name: get the cephadm ssh pub key
  command: "cephadm shell {{ '--fsid ' + fsid if fsid is defined else '' }} ceph cephadm get-pub-key"
  changed_when: false
  register: cephadm_get_pub_key
  when: cephadm_pubkey_path is undefined

- name: allow ssh public key for {{ cephadm_ssh_user | default('root') }} account
  authorized_key:
    user: "{{ cephadm_ssh_user | default('root') }}"
    key: "{{ lookup('file', cephadm_pubkey_path) if cephadm_pubkey_path is defined else cephadm_get_pub_key.stdout }}"

- name: Fetch FSID of the Ceph cluster
  command: ceph fsid
  register: ceph_fsid
  changed_when: false

- name: Set cephadm SSH user to {{ cephadm_ssh_user }}
  command: >
    cephadm shell --fsid {{ ceph_fsid.stdout }} ceph cephadm set-user {{ cephadm_ssh_user | default('root') }}
  changed_when: false

- name: Copy SSH public key to each client host
  ansible.builtin.shell: |
    ssh-copy-id -o StrictHostKeyChecking=no -f -i {{ cephadm_pubkey_path }} {{ cephadm_ssh_user }}@{{ item }} && \
    (echo "SSH key copied successfully to {{ item }}." || echo "Failed to copy SSH key to {{ item }}.")
  loop: "{{ groups['clients'] }}"
  loop_control:
    loop_var: item
  become_user: {{ cephadm_ssh_user }}