---
- name: Setup initial Ceph configuration
  block:
    - name: Add SSH user to the sudo group
      ansible.builtin.user:
        name: "{{ ssh_user }}"
        groups: sudo
        append: yes

    - name: Add SSH user to the docker group
      ansible.builtin.user:
        name: "{{ ssh_user }}"
        groups: docker
        append: yes

    - name: Add SSH user to the ceph group
      ansible.builtin.user:
        name: "{{ ssh_user }}"
        groups: ceph
        append: yes

    - name: Create a temporary Ceph configuration file
      copy:
        dest: "/tmp/ceph_temp_config.conf"
        content: |
          [global]
          osd crush chooseleaf type = {{ ceph_config.global.osd_crush_chooseleaf_type }}
          osd_pool_default_size = {{ ceph_config.global.osd_pool_default_size }}
      register: temp_config_file

    - name: Bootstrap the Ceph cluster
      ansible.builtin.command: |
        sudo cephadm bootstrap --mon-ip {{ hostvars[groups['admin'][0]]['ansible_host'] }} --cluster-network {{ cluster_network }}
        --ssh-user {{ ssh_user }} -c {{ temp_config_file.path }} --allow-overwrite --log-to-file

    - name: Distribute Cephadm SSH keys to all hosts
      include_tasks: distribute_ssh_keys.yml
      vars:
        cephadm_ssh_user: "{{ ssh_user }}"
        cephadm_pubkey_path: "{{ ssh_key }}"

    - name: Add and label hosts in the Ceph cluster
      include_tasks: add_host_and_label.yml

    - name: Prepare and add OSDs
      pause:
        seconds: 60

    - name: Add OSDs and Ensure They Are Ready
      include_tasks: add_osds_and_wait.yml
      when: inventory_hostname in groups['osds']

    - name: Label all OSD hosts with '_no_schedule'
      pause:
        seconds: 60

    - name: Apply '_no_schedule' Label to OSD Hosts
      include_tasks: label_osd_hosts_no_schedule.yml

    - name: Cleanup
      file:
        path: "{{ temp_config_file.path }}"
        state: absent
      when: temp_config_file is defined
